# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d30eaf1d4fc78203e41b25f172265655d18da06baffccc75293e0789532f925ef3461e585e85d75ab20f06e1b278f1008bc0ea227ba4eefd370639a1f03fda77

test:
  secret_key_base: a4b046a16015d4e9592c80a8cdcbfd501c2a7c10c31a5dd3afec6cae576c83e6d44f61913ebfdf4a07cda27a5af52b6279a80934071c9a91e5f716d8f1923b70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
